name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand('ping')'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install

      - name: Run Backend Tests
        working-directory: ./server
        env:
          MONGO_URI: mongodb://localhost:27017/testdb # Use a test database
          NODE_ENV: test
        run: npm test

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test
